Update windows crate to 0.35.0
robmikh/minesweeper-rs pull request #47
Opened 2022-04-16 13:24 UTC by arnabanimesh

2022-04-16 17:38 UTC, robmikh requested changes

2022-04-16 17:38 UTC, robmikh commented on src/window.rs
> -            .ok()?
Could you leave the error handling in place?

2022-04-16 17:40 UTC, robmikh requested changes

2022-04-16 17:40 UTC, robmikh commented on src/window.rs
> -        let instance = unsafe { GetModuleHandleW(None).ok()? };
Same here.

2022-04-16 20:03 UTC, robmikh commented
Oh strange, I see you did that now because of compilation errors... I'll accept this and figure out what can be done about that.

2022-04-16 20:03 UTC, robmikh approved these changes

2022-04-16 20:06 UTC, merged

2022-04-18 16:22 UTC, kennykerr commented
`HINSTANCE` was affected by a win32 metadata bug https://github.com/microsoft/win32metadata/issues/863

2022-04-26 18:56 UTC, kennykerr commented
[0.36.0](https://github.com/microsoft/windows-rs/releases/tag/0.36.0) has been released and includes this fix.